package com.daaje.model;
// Generated 6 sept. 2023, 13:51:33 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Apprenant generated by hbm2java
 */
@Entity
@Table(name = "apprenant", catalog = "sigca_bd")
public class Apprenant implements java.io.Serializable {

	private Integer idApprenant;
	private Activite activite;
	private Genre genre;
	private String codeApprenant;
	private String nomApprenant;
	private String prenomApprenant;
	private Date dateNaissApprenant;
	private String telephoneApprenant;
	private String adresseApprenant;
	private String mailApprenant;

	public Apprenant() {
	}

	public Apprenant(Genre genre) {
		this.genre = genre;
	}

	public Apprenant(Activite activite, Genre genre, String codeApprenant, String nomApprenant, String prenomApprenant,
			Date dateNaissApprenant, String telephoneApprenant, String adresseApprenant, String mailApprenant) {
		this.activite = activite;
		this.genre = genre;
		this.codeApprenant = codeApprenant;
		this.nomApprenant = nomApprenant;
		this.prenomApprenant = prenomApprenant;
		this.dateNaissApprenant = dateNaissApprenant;
		this.telephoneApprenant = telephoneApprenant;
		this.adresseApprenant = adresseApprenant;
		this.mailApprenant = mailApprenant;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_APPRENANT", unique = true, nullable = false)
	public Integer getIdApprenant() {
		return this.idApprenant;
	}

	public void setIdApprenant(Integer idApprenant) {
		this.idApprenant = idApprenant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTIVITE")
	public Activite getActivite() {
		return this.activite;
	}

	public void setActivite(Activite activite) {
		this.activite = activite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GENRE", nullable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	@Column(name = "CODE_APPRENANT", length = 10)
	public String getCodeApprenant() {
		return this.codeApprenant;
	}

	public void setCodeApprenant(String codeApprenant) {
		this.codeApprenant = codeApprenant;
	}

	@Column(name = "NOM_APPRENANT", length = 30)
	public String getNomApprenant() {
		return this.nomApprenant;
	}

	public void setNomApprenant(String nomApprenant) {
		this.nomApprenant = nomApprenant;
	}

	@Column(name = "PRENOM_APPRENANT", length = 30)
	public String getPrenomApprenant() {
		return this.prenomApprenant;
	}

	public void setPrenomApprenant(String prenomApprenant) {
		this.prenomApprenant = prenomApprenant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISS_APPRENANT", length = 10)
	public Date getDateNaissApprenant() {
		return this.dateNaissApprenant;
	}

	public void setDateNaissApprenant(Date dateNaissApprenant) {
		this.dateNaissApprenant = dateNaissApprenant;
	}

	@Column(name = "TELEPHONE_APPRENANT", length = 10)
	public String getTelephoneApprenant() {
		return this.telephoneApprenant;
	}

	public void setTelephoneApprenant(String telephoneApprenant) {
		this.telephoneApprenant = telephoneApprenant;
	}

	@Column(name = "ADRESSE_APPRENANT", length = 20)
	public String getAdresseApprenant() {
		return this.adresseApprenant;
	}

	public void setAdresseApprenant(String adresseApprenant) {
		this.adresseApprenant = adresseApprenant;
	}

	@Column(name = "MAIL_APPRENANT", length = 30)
	public String getMailApprenant() {
		return this.mailApprenant;
	}

	public void setMailApprenant(String mailApprenant) {
		this.mailApprenant = mailApprenant;
	}

}
