package com.daaje.model;
// Generated 10 janv. 2024, 16:03:56 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Centre generated by hbm2java
 */
@Entity
@Table(name = "centre", catalog = "sygca_bd")
public class Centre implements java.io.Serializable {

	private Integer idCentre;
	private Ecole ecole;
	private Iep iep;
	private LocaliteDImplantation localiteDImplantation;
	private Nature nature;
	private NatureProjet natureProjet;
	private Promoteur promoteur;
	private Responsable responsable;
	private String codeCentre;
	private String nomCentre;
	private String abreviationNomCentre;
	private String telephoneCentre;
	private String adresseCentre;
	private String mailCentre;
	private String droitOuvertureCentre;
	private Boolean permanent;
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);
	private Set<Inscription> inscriptions = new HashSet<Inscription>(0);

	public Centre() {
	}

	public Centre(Iep iep, LocaliteDImplantation localiteDImplantation, Nature nature, NatureProjet natureProjet,
			Promoteur promoteur, Responsable responsable) {
		this.iep = iep;
		this.localiteDImplantation = localiteDImplantation;
		this.nature = nature;
		this.natureProjet = natureProjet;
		this.promoteur = promoteur;
		this.responsable = responsable;
	}

	public Centre(Ecole ecole, Iep iep, LocaliteDImplantation localiteDImplantation, Nature nature,
			NatureProjet natureProjet, Promoteur promoteur, Responsable responsable, String codeCentre,
			String nomCentre, String abreviationNomCentre, String telephoneCentre, String adresseCentre,
			String mailCentre, String droitOuvertureCentre, Boolean permanent, Set<Enseigner> enseigners,
			Set<Inscription> inscriptions) {
		this.ecole = ecole;
		this.iep = iep;
		this.localiteDImplantation = localiteDImplantation;
		this.nature = nature;
		this.natureProjet = natureProjet;
		this.promoteur = promoteur;
		this.responsable = responsable;
		this.codeCentre = codeCentre;
		this.nomCentre = nomCentre;
		this.abreviationNomCentre = abreviationNomCentre;
		this.telephoneCentre = telephoneCentre;
		this.adresseCentre = adresseCentre;
		this.mailCentre = mailCentre;
		this.droitOuvertureCentre = droitOuvertureCentre;
		this.permanent = permanent;
		this.enseigners = enseigners;
		this.inscriptions = inscriptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CENTRE", unique = true, nullable = false)
	public Integer getIdCentre() {
		return this.idCentre;
	}

	public void setIdCentre(Integer idCentre) {
		this.idCentre = idCentre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ECOLE")
	public Ecole getEcole() {
		return this.ecole;
	}

	public void setEcole(Ecole ecole) {
		this.ecole = ecole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_IEP", nullable = false)
	public Iep getIep() {
		return this.iep;
	}

	public void setIep(Iep iep) {
		this.iep = iep;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_LOCALITE", nullable = false)
	public LocaliteDImplantation getLocaliteDImplantation() {
		return this.localiteDImplantation;
	}

	public void setLocaliteDImplantation(LocaliteDImplantation localiteDImplantation) {
		this.localiteDImplantation = localiteDImplantation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_NATURE", nullable = false)
	public Nature getNature() {
		return this.nature;
	}

	public void setNature(Nature nature) {
		this.nature = nature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NATURE_PROJET", nullable = false)
	public NatureProjet getNatureProjet() {
		return this.natureProjet;
	}

	public void setNatureProjet(NatureProjet natureProjet) {
		this.natureProjet = natureProjet;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PROMOTEUR", nullable = false)
	public Promoteur getPromoteur() {
		return this.promoteur;
	}

	public void setPromoteur(Promoteur promoteur) {
		this.promoteur = promoteur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RESPONSABLE", nullable = false)
	public Responsable getResponsable() {
		return this.responsable;
	}

	public void setResponsable(Responsable responsable) {
		this.responsable = responsable;
	}

	@Column(name = "CODE_CENTRE", length = 10)
	public String getCodeCentre() {
		return this.codeCentre;
	}

	public void setCodeCentre(String codeCentre) {
		this.codeCentre = codeCentre;
	}

	@Column(name = "NOM_CENTRE", length = 150)
	public String getNomCentre() {
		return this.nomCentre;
	}

	public void setNomCentre(String nomCentre) {
		this.nomCentre = nomCentre;
	}

	@Column(name = "ABREVIATION_NOM_CENTRE", length = 10)
	public String getAbreviationNomCentre() {
		return this.abreviationNomCentre;
	}

	public void setAbreviationNomCentre(String abreviationNomCentre) {
		this.abreviationNomCentre = abreviationNomCentre;
	}

	@Column(name = "TELEPHONE_CENTRE", length = 10)
	public String getTelephoneCentre() {
		return this.telephoneCentre;
	}

	public void setTelephoneCentre(String telephoneCentre) {
		this.telephoneCentre = telephoneCentre;
	}

	@Column(name = "ADRESSE_CENTRE", length = 20)
	public String getAdresseCentre() {
		return this.adresseCentre;
	}

	public void setAdresseCentre(String adresseCentre) {
		this.adresseCentre = adresseCentre;
	}

	@Column(name = "MAIL_CENTRE", length = 30)
	public String getMailCentre() {
		return this.mailCentre;
	}

	public void setMailCentre(String mailCentre) {
		this.mailCentre = mailCentre;
	}

	@Column(name = "DROIT_OUVERTURE_CENTRE", length = 200)
	public String getDroitOuvertureCentre() {
		return this.droitOuvertureCentre;
	}

	public void setDroitOuvertureCentre(String droitOuvertureCentre) {
		this.droitOuvertureCentre = droitOuvertureCentre;
	}

	@Column(name = "PERMANENT")
	public Boolean getPermanent() {
		return this.permanent;
	}

	public void setPermanent(Boolean permanent) {
		this.permanent = permanent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centre")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centre")
	public Set<Inscription> getInscriptions() {
		return this.inscriptions;
	}

	public void setInscriptions(Set<Inscription> inscriptions) {
		this.inscriptions = inscriptions;
	}

}
