package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Centre generated by hbm2java
 */
@Entity
@Table(name = "centre", catalog = "sygca_bd")
public class Centre implements java.io.Serializable {

	private Integer idCentre;
	private int idPromoteur;
	private int idDepartement;
	private int idCommune;
	private int attributIdIepp16;
	private int idNatureProjet;
	private int idNature;
	private int idPrefecture;
	private int idLocalite;
	private int idEnseigner;
	private String codeCentre;
	private String nomCentre;
	private String abreviationNomCentre;
	private String telephoneCentre;
	private String adresseCentre;
	private String mailCentre;
	private String droitOuvertureCentre;

	public Centre() {
	}

	public Centre(int idPromoteur, int idDepartement, int idCommune, int attributIdIepp16, int idNatureProjet,
			int idNature, int idPrefecture, int idLocalite, int idEnseigner) {
		this.idPromoteur = idPromoteur;
		this.idDepartement = idDepartement;
		this.idCommune = idCommune;
		this.attributIdIepp16 = attributIdIepp16;
		this.idNatureProjet = idNatureProjet;
		this.idNature = idNature;
		this.idPrefecture = idPrefecture;
		this.idLocalite = idLocalite;
		this.idEnseigner = idEnseigner;
	}

	public Centre(int idPromoteur, int idDepartement, int idCommune, int attributIdIepp16, int idNatureProjet,
			int idNature, int idPrefecture, int idLocalite, int idEnseigner, String codeCentre, String nomCentre,
			String abreviationNomCentre, String telephoneCentre, String adresseCentre, String mailCentre,
			String droitOuvertureCentre) {
		this.idPromoteur = idPromoteur;
		this.idDepartement = idDepartement;
		this.idCommune = idCommune;
		this.attributIdIepp16 = attributIdIepp16;
		this.idNatureProjet = idNatureProjet;
		this.idNature = idNature;
		this.idPrefecture = idPrefecture;
		this.idLocalite = idLocalite;
		this.idEnseigner = idEnseigner;
		this.codeCentre = codeCentre;
		this.nomCentre = nomCentre;
		this.abreviationNomCentre = abreviationNomCentre;
		this.telephoneCentre = telephoneCentre;
		this.adresseCentre = adresseCentre;
		this.mailCentre = mailCentre;
		this.droitOuvertureCentre = droitOuvertureCentre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_CENTRE", unique = true, nullable = false)
	public Integer getIdCentre() {
		return this.idCentre;
	}

	public void setIdCentre(Integer idCentre) {
		this.idCentre = idCentre;
	}

	@Column(name = "ID_PROMOTEUR", nullable = false)
	public int getIdPromoteur() {
		return this.idPromoteur;
	}

	public void setIdPromoteur(int idPromoteur) {
		this.idPromoteur = idPromoteur;
	}

	@Column(name = "ID_DEPARTEMENT", nullable = false)
	public int getIdDepartement() {
		return this.idDepartement;
	}

	public void setIdDepartement(int idDepartement) {
		this.idDepartement = idDepartement;
	}

	@Column(name = "ID_COMMUNE", nullable = false)
	public int getIdCommune() {
		return this.idCommune;
	}

	public void setIdCommune(int idCommune) {
		this.idCommune = idCommune;
	}

	@Column(name = "ATTRIBUT_ID_IEPP16", nullable = false)
	public int getAttributIdIepp16() {
		return this.attributIdIepp16;
	}

	public void setAttributIdIepp16(int attributIdIepp16) {
		this.attributIdIepp16 = attributIdIepp16;
	}

	@Column(name = "ID_NATURE_PROJET", nullable = false)
	public int getIdNatureProjet() {
		return this.idNatureProjet;
	}

	public void setIdNatureProjet(int idNatureProjet) {
		this.idNatureProjet = idNatureProjet;
	}

	@Column(name = "ID_NATURE", nullable = false)
	public int getIdNature() {
		return this.idNature;
	}

	public void setIdNature(int idNature) {
		this.idNature = idNature;
	}

	@Column(name = "ID_PREFECTURE", nullable = false)
	public int getIdPrefecture() {
		return this.idPrefecture;
	}

	public void setIdPrefecture(int idPrefecture) {
		this.idPrefecture = idPrefecture;
	}

	@Column(name = "ID_LOCALITE", nullable = false)
	public int getIdLocalite() {
		return this.idLocalite;
	}

	public void setIdLocalite(int idLocalite) {
		this.idLocalite = idLocalite;
	}

	@Column(name = "ID_ENSEIGNER", nullable = false)
	public int getIdEnseigner() {
		return this.idEnseigner;
	}

	public void setIdEnseigner(int idEnseigner) {
		this.idEnseigner = idEnseigner;
	}

	@Column(name = "CODE_CENTRE", length = 10)
	public String getCodeCentre() {
		return this.codeCentre;
	}

	public void setCodeCentre(String codeCentre) {
		this.codeCentre = codeCentre;
	}

	@Column(name = "NOM_CENTRE", length = 70)
	public String getNomCentre() {
		return this.nomCentre;
	}

	public void setNomCentre(String nomCentre) {
		this.nomCentre = nomCentre;
	}

	@Column(name = "ABREVIATION_NOM_CENTRE", length = 10)
	public String getAbreviationNomCentre() {
		return this.abreviationNomCentre;
	}

	public void setAbreviationNomCentre(String abreviationNomCentre) {
		this.abreviationNomCentre = abreviationNomCentre;
	}

	@Column(name = "TELEPHONE_CENTRE", length = 10)
	public String getTelephoneCentre() {
		return this.telephoneCentre;
	}

	public void setTelephoneCentre(String telephoneCentre) {
		this.telephoneCentre = telephoneCentre;
	}

	@Column(name = "ADRESSE_CENTRE", length = 20)
	public String getAdresseCentre() {
		return this.adresseCentre;
	}

	public void setAdresseCentre(String adresseCentre) {
		this.adresseCentre = adresseCentre;
	}

	@Column(name = "MAIL_CENTRE", length = 30)
	public String getMailCentre() {
		return this.mailCentre;
	}

	public void setMailCentre(String mailCentre) {
		this.mailCentre = mailCentre;
	}

	@Column(name = "DROIT_OUVERTURE_CENTRE", length = 100)
	public String getDroitOuvertureCentre() {
		return this.droitOuvertureCentre;
	}

	public void setDroitOuvertureCentre(String droitOuvertureCentre) {
		this.droitOuvertureCentre = droitOuvertureCentre;
	}

}
