package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commune generated by hbm2java
 */
@Entity
@Table(name = "commune", catalog = "sygca_bd")
public class Commune implements java.io.Serializable {

	private Integer idCommune;
	private String codeCommune;
	private String nomCommune;

	public Commune() {
	}

	public Commune(String codeCommune, String nomCommune) {
		this.codeCommune = codeCommune;
		this.nomCommune = nomCommune;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_COMMUNE", unique = true, nullable = false)
	public Integer getIdCommune() {
		return this.idCommune;
	}

	public void setIdCommune(Integer idCommune) {
		this.idCommune = idCommune;
	}

	@Column(name = "CODE_COMMUNE", length = 10)
	public String getCodeCommune() {
		return this.codeCommune;
	}

	public void setCodeCommune(String codeCommune) {
		this.codeCommune = codeCommune;
	}

	@Column(name = "NOM_COMMUNE", length = 30)
	public String getNomCommune() {
		return this.nomCommune;
	}

	public void setNomCommune(String nomCommune) {
		this.nomCommune = nomCommune;
	}

}
