package com.daaje.model;
// Generated 6 sept. 2023, 13:51:33 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "sigca_bd")
public class Departement implements java.io.Serializable {

	private Integer idDepartement;
	private String codeDepartement;
	private String nomDepartement;
	private String mailDepartement;
	private Set<Centre> centres = new HashSet<Centre>(0);

	public Departement() {
	}

	public Departement(String codeDepartement, String nomDepartement, String mailDepartement, Set<Centre> centres) {
		this.codeDepartement = codeDepartement;
		this.nomDepartement = nomDepartement;
		this.mailDepartement = mailDepartement;
		this.centres = centres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_DEPARTEMENT", unique = true, nullable = false)
	public Integer getIdDepartement() {
		return this.idDepartement;
	}

	public void setIdDepartement(Integer idDepartement) {
		this.idDepartement = idDepartement;
	}

	@Column(name = "CODE_DEPARTEMENT", length = 10)
	public String getCodeDepartement() {
		return this.codeDepartement;
	}

	public void setCodeDepartement(String codeDepartement) {
		this.codeDepartement = codeDepartement;
	}

	@Column(name = "NOM_DEPARTEMENT", length = 30)
	public String getNomDepartement() {
		return this.nomDepartement;
	}

	public void setNomDepartement(String nomDepartement) {
		this.nomDepartement = nomDepartement;
	}

	@Column(name = "MAIL_DEPARTEMENT", length = 30)
	public String getMailDepartement() {
		return this.mailDepartement;
	}

	public void setMailDepartement(String mailDepartement) {
		this.mailDepartement = mailDepartement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	public Set<Centre> getCentres() {
		return this.centres;
	}

	public void setCentres(Set<Centre> centres) {
		this.centres = centres;
	}

}
