package com.daaje.model;
// Generated 2 nov. 2023, 15:04:15 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Drena generated by hbm2java
 */
@Entity
@Table(name = "drena", catalog = "sygca_bd")
public class Drena implements java.io.Serializable {

	private Integer idDrena;
	private String codeDrena;
	private String nomDrena;
	private String mailDrena;
	private String telephone;
	private Set<Iep> ieps = new HashSet<Iep>(0);
	private Set<ServiceResponsable> serviceResponsables = new HashSet<ServiceResponsable>(0);
	private Set<Departement> departements = new HashSet<Departement>(0);

	public Drena() {
	}

	public Drena(String codeDrena, String nomDrena, String mailDrena, String telephone, Set<Iep> ieps,
			Set<ServiceResponsable> serviceResponsables, Set<Departement> departements) {
		this.codeDrena = codeDrena;
		this.nomDrena = nomDrena;
		this.mailDrena = mailDrena;
		this.telephone = telephone;
		this.ieps = ieps;
		this.serviceResponsables = serviceResponsables;
		this.departements = departements;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_DRENA", unique = true, nullable = false)
	public Integer getIdDrena() {
		return this.idDrena;
	}

	public void setIdDrena(Integer idDrena) {
		this.idDrena = idDrena;
	}

	@Column(name = "CODE_DRENA", length = 10)
	public String getCodeDrena() {
		return this.codeDrena;
	}

	public void setCodeDrena(String codeDrena) {
		this.codeDrena = codeDrena;
	}

	@Column(name = "NOM_DRENA", length = 30)
	public String getNomDrena() {
		return this.nomDrena;
	}

	public void setNomDrena(String nomDrena) {
		this.nomDrena = nomDrena;
	}

	@Column(name = "MAIL_DRENA", length = 30)
	public String getMailDrena() {
		return this.mailDrena;
	}

	public void setMailDrena(String mailDrena) {
		this.mailDrena = mailDrena;
	}

	@Column(name = "TELEPHONE", length = 15)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drena")
	public Set<Iep> getIeps() {
		return this.ieps;
	}

	public void setIeps(Set<Iep> ieps) {
		this.ieps = ieps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drena")
	public Set<ServiceResponsable> getServiceResponsables() {
		return this.serviceResponsables;
	}

	public void setServiceResponsables(Set<ServiceResponsable> serviceResponsables) {
		this.serviceResponsables = serviceResponsables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drena")
	public Set<Departement> getDepartements() {
		return this.departements;
	}

	public void setDepartements(Set<Departement> departements) {
		this.departements = departements;
	}

}
