package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enseigner generated by hbm2java
 */
@Entity
@Table(name = "enseigner", catalog = "sygca_bd")
public class Enseigner implements java.io.Serializable {

	private Integer idEnseigner;
	private int idNiveauFormation;
	private int idCampagne;
	private int idAnimateur;
	private Integer idCentre;
	private String codeEnseigner;

	public Enseigner() {
	}

	public Enseigner(int idNiveauFormation, int idCampagne, int idAnimateur) {
		this.idNiveauFormation = idNiveauFormation;
		this.idCampagne = idCampagne;
		this.idAnimateur = idAnimateur;
	}

	public Enseigner(int idNiveauFormation, int idCampagne, int idAnimateur, Integer idCentre, String codeEnseigner) {
		this.idNiveauFormation = idNiveauFormation;
		this.idCampagne = idCampagne;
		this.idAnimateur = idAnimateur;
		this.idCentre = idCentre;
		this.codeEnseigner = codeEnseigner;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ENSEIGNER", unique = true, nullable = false)
	public Integer getIdEnseigner() {
		return this.idEnseigner;
	}

	public void setIdEnseigner(Integer idEnseigner) {
		this.idEnseigner = idEnseigner;
	}

	@Column(name = "ID_NIVEAU_FORMATION", nullable = false)
	public int getIdNiveauFormation() {
		return this.idNiveauFormation;
	}

	public void setIdNiveauFormation(int idNiveauFormation) {
		this.idNiveauFormation = idNiveauFormation;
	}

	@Column(name = "ID_CAMPAGNE", nullable = false)
	public int getIdCampagne() {
		return this.idCampagne;
	}

	public void setIdCampagne(int idCampagne) {
		this.idCampagne = idCampagne;
	}

	@Column(name = "ID_ANIMATEUR", nullable = false)
	public int getIdAnimateur() {
		return this.idAnimateur;
	}

	public void setIdAnimateur(int idAnimateur) {
		this.idAnimateur = idAnimateur;
	}

	@Column(name = "ID_CENTRE")
	public Integer getIdCentre() {
		return this.idCentre;
	}

	public void setIdCentre(Integer idCentre) {
		this.idCentre = idCentre;
	}

	@Column(name = "CODE_ENSEIGNER", length = 10)
	public String getCodeEnseigner() {
		return this.codeEnseigner;
	}

	public void setCodeEnseigner(String codeEnseigner) {
		this.codeEnseigner = codeEnseigner;
	}

}
