package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fonction generated by hbm2java
 */
@Entity
@Table(name = "fonction", catalog = "sygca_bd")
public class Fonction implements java.io.Serializable {

	private Integer idFonction;
	private String codeFonction;
	private String libelleFonction;

	public Fonction() {
	}

	public Fonction(String codeFonction, String libelleFonction) {
		this.codeFonction = codeFonction;
		this.libelleFonction = libelleFonction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_FONCTION", unique = true, nullable = false)
	public Integer getIdFonction() {
		return this.idFonction;
	}

	public void setIdFonction(Integer idFonction) {
		this.idFonction = idFonction;
	}

	@Column(name = "CODE_FONCTION", length = 10)
	public String getCodeFonction() {
		return this.codeFonction;
	}

	public void setCodeFonction(String codeFonction) {
		this.codeFonction = codeFonction;
	}

	@Column(name = "LIBELLE_FONCTION", length = 30)
	public String getLibelleFonction() {
		return this.libelleFonction;
	}

	public void setLibelleFonction(String libelleFonction) {
		this.libelleFonction = libelleFonction;
	}

}
