package com.daaje.model;
// Generated 2 nov. 2023, 15:04:15 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fonction generated by hbm2java
 */
@Entity
@Table(name = "fonction", catalog = "sygca_bd")
public class Fonction implements java.io.Serializable {

	private Integer idFonction;
	private String codeFonction;
	private String libelleFonction;
	private Set<Responsable> responsables = new HashSet<Responsable>(0);

	public Fonction() {
	}

	public Fonction(String codeFonction, String libelleFonction, Set<Responsable> responsables) {
		this.codeFonction = codeFonction;
		this.libelleFonction = libelleFonction;
		this.responsables = responsables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_FONCTION", unique = true, nullable = false)
	public Integer getIdFonction() {
		return this.idFonction;
	}

	public void setIdFonction(Integer idFonction) {
		this.idFonction = idFonction;
	}

	@Column(name = "CODE_FONCTION", length = 10)
	public String getCodeFonction() {
		return this.codeFonction;
	}

	public void setCodeFonction(String codeFonction) {
		this.codeFonction = codeFonction;
	}

	@Column(name = "LIBELLE_FONCTION", length = 30)
	public String getLibelleFonction() {
		return this.libelleFonction;
	}

	public void setLibelleFonction(String libelleFonction) {
		this.libelleFonction = libelleFonction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fonction")
	public Set<Responsable> getResponsables() {
		return this.responsables;
	}

	public void setResponsables(Set<Responsable> responsables) {
		this.responsables = responsables;
	}

}
