package com.daaje.model;
// Generated 2 nov. 2023, 15:04:15 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", catalog = "sygca_bd")
public class Genre implements java.io.Serializable {

	private Integer idGenre;
	private String codeGenre;
	private String libelleGenre;
	private Set<Animateur> animateurs = new HashSet<Animateur>(0);
	private Set<Apprenant> apprenants = new HashSet<Apprenant>(0);

	public Genre() {
	}

	public Genre(String codeGenre, String libelleGenre, Set<Animateur> animateurs, Set<Apprenant> apprenants) {
		this.codeGenre = codeGenre;
		this.libelleGenre = libelleGenre;
		this.animateurs = animateurs;
		this.apprenants = apprenants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_GENRE", unique = true, nullable = false)
	public Integer getIdGenre() {
		return this.idGenre;
	}

	public void setIdGenre(Integer idGenre) {
		this.idGenre = idGenre;
	}

	@Column(name = "CODE_GENRE", length = 10)
	public String getCodeGenre() {
		return this.codeGenre;
	}

	public void setCodeGenre(String codeGenre) {
		this.codeGenre = codeGenre;
	}

	@Column(name = "LIBELLE_GENRE", length = 10)
	public String getLibelleGenre() {
		return this.libelleGenre;
	}

	public void setLibelleGenre(String libelleGenre) {
		this.libelleGenre = libelleGenre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Animateur> getAnimateurs() {
		return this.animateurs;
	}

	public void setAnimateurs(Set<Animateur> animateurs) {
		this.animateurs = animateurs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Apprenant> getApprenants() {
		return this.apprenants;
	}

	public void setApprenants(Set<Apprenant> apprenants) {
		this.apprenants = apprenants;
	}

}
