package com.daaje.model;
// Generated 8 avr. 2024, 14:52:14 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Iep generated by hbm2java
 */
@Entity
@Table(name = "iep", catalog = "sygca_bd")
public class Iep implements java.io.Serializable {

	private Integer idIep;
	private Drena drena;
	private String codeIep;
	private String nomIep;
	private String mailIep;
	private String telephoneIep;
	private Set<Centre> centres = new HashSet<Centre>(0);
	private Set<ServiceResponsable> serviceResponsables = new HashSet<ServiceResponsable>(0);
	private Set<Ecole> ecoles = new HashSet<Ecole>(0);

	public Iep() {
	}

	public Iep(Drena drena) {
		this.drena = drena;
	}

	public Iep(Drena drena, String codeIep, String nomIep, String mailIep, String telephoneIep, Set<Centre> centres,
			Set<ServiceResponsable> serviceResponsables, Set<Ecole> ecoles) {
		this.drena = drena;
		this.codeIep = codeIep;
		this.nomIep = nomIep;
		this.mailIep = mailIep;
		this.telephoneIep = telephoneIep;
		this.centres = centres;
		this.serviceResponsables = serviceResponsables;
		this.ecoles = ecoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_IEP", unique = true, nullable = false)
	public Integer getIdIep() {
		return this.idIep;
	}

	public void setIdIep(Integer idIep) {
		this.idIep = idIep;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_DRENA", nullable = false)
	public Drena getDrena() {
		return this.drena;
	}

	public void setDrena(Drena drena) {
		this.drena = drena;
	}

	@Column(name = "CODE_IEP", length = 10)
	public String getCodeIep() {
		return this.codeIep;
	}

	public void setCodeIep(String codeIep) {
		this.codeIep = codeIep;
	}

	@Column(name = "NOM_IEP", length = 30)
	public String getNomIep() {
		return this.nomIep;
	}

	public void setNomIep(String nomIep) {
		this.nomIep = nomIep;
	}

	@Column(name = "MAIL_IEP", length = 30)
	public String getMailIep() {
		return this.mailIep;
	}

	public void setMailIep(String mailIep) {
		this.mailIep = mailIep;
	}

	@Column(name = "TELEPHONE_IEP", length = 10)
	public String getTelephoneIep() {
		return this.telephoneIep;
	}

	public void setTelephoneIep(String telephoneIep) {
		this.telephoneIep = telephoneIep;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "iep")
	public Set<Centre> getCentres() {
		return this.centres;
	}

	public void setCentres(Set<Centre> centres) {
		this.centres = centres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iep")
	public Set<ServiceResponsable> getServiceResponsables() {
		return this.serviceResponsables;
	}

	public void setServiceResponsables(Set<ServiceResponsable> serviceResponsables) {
		this.serviceResponsables = serviceResponsables;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "iep")
	public Set<Ecole> getEcoles() {
		return this.ecoles;
	}

	public void setEcoles(Set<Ecole> ecoles) {
		this.ecoles = ecoles;
	}

}
