package com.daaje.model;
// Generated 6 sept. 2023, 13:51:33 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Iepp generated by hbm2java
 */
@Entity
@Table(name = "iepp", catalog = "sigca_bd")
public class Iepp implements java.io.Serializable {

	private Integer attributIdIepp16;
	private Drena drena;
	private String codeIepp;
	private String nomIepp;
	private String mailIepp;
	private Set<Centre> centres = new HashSet<Centre>(0);

	public Iepp() {
	}

	public Iepp(Drena drena) {
		this.drena = drena;
	}

	public Iepp(Drena drena, String codeIepp, String nomIepp, String mailIepp, Set<Centre> centres) {
		this.drena = drena;
		this.codeIepp = codeIepp;
		this.nomIepp = nomIepp;
		this.mailIepp = mailIepp;
		this.centres = centres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ATTRIBUT_ID_IEPP16", unique = true, nullable = false)
	public Integer getAttributIdIepp16() {
		return this.attributIdIepp16;
	}

	public void setAttributIdIepp16(Integer attributIdIepp16) {
		this.attributIdIepp16 = attributIdIepp16;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DRENA", nullable = false)
	public Drena getDrena() {
		return this.drena;
	}

	public void setDrena(Drena drena) {
		this.drena = drena;
	}

	@Column(name = "CODE_IEPP", length = 10)
	public String getCodeIepp() {
		return this.codeIepp;
	}

	public void setCodeIepp(String codeIepp) {
		this.codeIepp = codeIepp;
	}

	@Column(name = "NOM_IEPP", length = 30)
	public String getNomIepp() {
		return this.nomIepp;
	}

	public void setNomIepp(String nomIepp) {
		this.nomIepp = nomIepp;
	}

	@Column(name = "MAIL_IEPP", length = 30)
	public String getMailIepp() {
		return this.mailIepp;
	}

	public void setMailIepp(String mailIepp) {
		this.mailIepp = mailIepp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iepp")
	public Set<Centre> getCentres() {
		return this.centres;
	}

	public void setCentres(Set<Centre> centres) {
		this.centres = centres;
	}

}
