package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Iepp generated by hbm2java
 */
@Entity
@Table(name = "iepp", catalog = "sygca_bd")
public class Iepp implements java.io.Serializable {

	private Integer attributIdIepp16;
	private int idDrena;
	private String codeIepp;
	private String nomIepp;
	private String mailIepp;

	public Iepp() {
	}

	public Iepp(int idDrena) {
		this.idDrena = idDrena;
	}

	public Iepp(int idDrena, String codeIepp, String nomIepp, String mailIepp) {
		this.idDrena = idDrena;
		this.codeIepp = codeIepp;
		this.nomIepp = nomIepp;
		this.mailIepp = mailIepp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ATTRIBUT_ID_IEPP16", unique = true, nullable = false)
	public Integer getAttributIdIepp16() {
		return this.attributIdIepp16;
	}

	public void setAttributIdIepp16(Integer attributIdIepp16) {
		this.attributIdIepp16 = attributIdIepp16;
	}

	@Column(name = "ID_DRENA", nullable = false)
	public int getIdDrena() {
		return this.idDrena;
	}

	public void setIdDrena(int idDrena) {
		this.idDrena = idDrena;
	}

	@Column(name = "CODE_IEPP", length = 10)
	public String getCodeIepp() {
		return this.codeIepp;
	}

	public void setCodeIepp(String codeIepp) {
		this.codeIepp = codeIepp;
	}

	@Column(name = "NOM_IEPP", length = 30)
	public String getNomIepp() {
		return this.nomIepp;
	}

	public void setNomIepp(String nomIepp) {
		this.nomIepp = nomIepp;
	}

	@Column(name = "MAIL_IEPP", length = 30)
	public String getMailIepp() {
		return this.mailIepp;
	}

	public void setMailIepp(String mailIepp) {
		this.mailIepp = mailIepp;
	}

}
