package com.daaje.model;
// Generated 8 avr. 2024, 14:52:14 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscription generated by hbm2java
 */
@Entity
@Table(name = "inscription", catalog = "sygca_bd")
public class Inscription implements java.io.Serializable {

	private Integer idInscription;
	private Apprenant apprenant;
	private Campagne campagne;
	private Centre centre;
	private NiveauFormation niveauFormation;
	private String codeInscription;
	private Date dateInscription;

	public Inscription() {
	}

	public Inscription(Apprenant apprenant, Campagne campagne, Centre centre) {
		this.apprenant = apprenant;
		this.campagne = campagne;
		this.centre = centre;
	}

	public Inscription(Apprenant apprenant, Campagne campagne, Centre centre, NiveauFormation niveauFormation,
			String codeInscription, Date dateInscription) {
		this.apprenant = apprenant;
		this.campagne = campagne;
		this.centre = centre;
		this.niveauFormation = niveauFormation;
		this.codeInscription = codeInscription;
		this.dateInscription = dateInscription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_INSCRIPTION", unique = true, nullable = false)
	public Integer getIdInscription() {
		return this.idInscription;
	}

	public void setIdInscription(Integer idInscription) {
		this.idInscription = idInscription;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_APPRENANT", nullable = false)
	public Apprenant getApprenant() {
		return this.apprenant;
	}

	public void setApprenant(Apprenant apprenant) {
		this.apprenant = apprenant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CAMPAGNE", nullable = false)
	public Campagne getCampagne() {
		return this.campagne;
	}

	public void setCampagne(Campagne campagne) {
		this.campagne = campagne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CENTRE", nullable = false)
	public Centre getCentre() {
		return this.centre;
	}

	public void setCentre(Centre centre) {
		this.centre = centre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_NIVEAU_FORMATION")
	public NiveauFormation getNiveauFormation() {
		return this.niveauFormation;
	}

	public void setNiveauFormation(NiveauFormation niveauFormation) {
		this.niveauFormation = niveauFormation;
	}

	@Column(name = "CODE_INSCRIPTION", length = 10)
	public String getCodeInscription() {
		return this.codeInscription;
	}

	public void setCodeInscription(String codeInscription) {
		this.codeInscription = codeInscription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_INSCRIPTION", length = 10)
	public Date getDateInscription() {
		return this.dateInscription;
	}

	public void setDateInscription(Date dateInscription) {
		this.dateInscription = dateInscription;
	}

}
