package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscription generated by hbm2java
 */
@Entity
@Table(name = "inscription", catalog = "sygca_bd")
public class Inscription implements java.io.Serializable {

	private Integer idInscription;
	private int idCentre;
	private int idApprenant;
	private int idCampagne;
	private int idNiveauFormation;
	private String codeInscription;
	private Date dateInscription;
	private Boolean clotureInscription;

	public Inscription() {
	}

	public Inscription(int idCentre, int idApprenant, int idCampagne, int idNiveauFormation) {
		this.idCentre = idCentre;
		this.idApprenant = idApprenant;
		this.idCampagne = idCampagne;
		this.idNiveauFormation = idNiveauFormation;
	}

	public Inscription(int idCentre, int idApprenant, int idCampagne, int idNiveauFormation, String codeInscription,
			Date dateInscription, Boolean clotureInscription) {
		this.idCentre = idCentre;
		this.idApprenant = idApprenant;
		this.idCampagne = idCampagne;
		this.idNiveauFormation = idNiveauFormation;
		this.codeInscription = codeInscription;
		this.dateInscription = dateInscription;
		this.clotureInscription = clotureInscription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_INSCRIPTION", unique = true, nullable = false)
	public Integer getIdInscription() {
		return this.idInscription;
	}

	public void setIdInscription(Integer idInscription) {
		this.idInscription = idInscription;
	}

	@Column(name = "ID_CENTRE", nullable = false)
	public int getIdCentre() {
		return this.idCentre;
	}

	public void setIdCentre(int idCentre) {
		this.idCentre = idCentre;
	}

	@Column(name = "ID_APPRENANT", nullable = false)
	public int getIdApprenant() {
		return this.idApprenant;
	}

	public void setIdApprenant(int idApprenant) {
		this.idApprenant = idApprenant;
	}

	@Column(name = "ID_CAMPAGNE", nullable = false)
	public int getIdCampagne() {
		return this.idCampagne;
	}

	public void setIdCampagne(int idCampagne) {
		this.idCampagne = idCampagne;
	}

	@Column(name = "ID_NIVEAU_FORMATION", nullable = false)
	public int getIdNiveauFormation() {
		return this.idNiveauFormation;
	}

	public void setIdNiveauFormation(int idNiveauFormation) {
		this.idNiveauFormation = idNiveauFormation;
	}

	@Column(name = "CODE_INSCRIPTION", length = 10)
	public String getCodeInscription() {
		return this.codeInscription;
	}

	public void setCodeInscription(String codeInscription) {
		this.codeInscription = codeInscription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_INSCRIPTION", length = 10)
	public Date getDateInscription() {
		return this.dateInscription;
	}

	public void setDateInscription(Date dateInscription) {
		this.dateInscription = dateInscription;
	}

	@Column(name = "CLOTURE_INSCRIPTION")
	public Boolean getClotureInscription() {
		return this.clotureInscription;
	}

	public void setClotureInscription(Boolean clotureInscription) {
		this.clotureInscription = clotureInscription;
	}

}
