package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LocaliteDImplantation generated by hbm2java
 */
@Entity
@Table(name = "localite_d_implantation", catalog = "sygca_bd")
public class LocaliteDImplantation implements java.io.Serializable {

	private Integer idLocalite;
	private String codeLocalite;
	private String nomLocalite;

	public LocaliteDImplantation() {
	}

	public LocaliteDImplantation(String codeLocalite, String nomLocalite) {
		this.codeLocalite = codeLocalite;
		this.nomLocalite = nomLocalite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LOCALITE", unique = true, nullable = false)
	public Integer getIdLocalite() {
		return this.idLocalite;
	}

	public void setIdLocalite(Integer idLocalite) {
		this.idLocalite = idLocalite;
	}

	@Column(name = "CODE_LOCALITE", length = 10)
	public String getCodeLocalite() {
		return this.codeLocalite;
	}

	public void setCodeLocalite(String codeLocalite) {
		this.codeLocalite = codeLocalite;
	}

	@Column(name = "NOM_LOCALITE", length = 30)
	public String getNomLocalite() {
		return this.nomLocalite;
	}

	public void setNomLocalite(String nomLocalite) {
		this.nomLocalite = nomLocalite;
	}

}
