package com.daaje.model;
// Generated 25 sept. 2023, 12:18:35 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocaliteDImplantation generated by hbm2java
 */
@Entity
@Table(name = "localite_d_implantation", catalog = "sygca_bd")
public class LocaliteDImplantation implements java.io.Serializable {

	private Integer idLocalite;
	private Commune commune;
	private SousPrefecture sousPrefecture;
	private String codeLocalite;
	private String nomLocalite;
	private Set<Centre> centres = new HashSet<Centre>(0);

	public LocaliteDImplantation() {
	}

	public LocaliteDImplantation(SousPrefecture sousPrefecture) {
		this.sousPrefecture = sousPrefecture;
	}

	public LocaliteDImplantation(Commune commune, SousPrefecture sousPrefecture, String codeLocalite,
			String nomLocalite, Set<Centre> centres) {
		this.commune = commune;
		this.sousPrefecture = sousPrefecture;
		this.codeLocalite = codeLocalite;
		this.nomLocalite = nomLocalite;
		this.centres = centres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LOCALITE", unique = true, nullable = false)
	public Integer getIdLocalite() {
		return this.idLocalite;
	}

	public void setIdLocalite(Integer idLocalite) {
		this.idLocalite = idLocalite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COMMUNE")
	public Commune getCommune() {
		return this.commune;
	}

	public void setCommune(Commune commune) {
		this.commune = commune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SOUS_PREFECTURE", nullable = false)
	public SousPrefecture getSousPrefecture() {
		return this.sousPrefecture;
	}

	public void setSousPrefecture(SousPrefecture sousPrefecture) {
		this.sousPrefecture = sousPrefecture;
	}

	@Column(name = "CODE_LOCALITE", length = 10)
	public String getCodeLocalite() {
		return this.codeLocalite;
	}

	public void setCodeLocalite(String codeLocalite) {
		this.codeLocalite = codeLocalite;
	}

	@Column(name = "NOM_LOCALITE", length = 30)
	public String getNomLocalite() {
		return this.nomLocalite;
	}

	public void setNomLocalite(String nomLocalite) {
		this.nomLocalite = nomLocalite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localiteDImplantation")
	public Set<Centre> getCentres() {
		return this.centres;
	}

	public void setCentres(Set<Centre> centres) {
		this.centres = centres;
	}

}
