package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nature generated by hbm2java
 */
@Entity
@Table(name = "nature", catalog = "sygca_bd")
public class Nature implements java.io.Serializable {

	private Integer idNature;
	private String codeNature;
	private String libelleNature;

	public Nature() {
	}

	public Nature(String codeNature, String libelleNature) {
		this.codeNature = codeNature;
		this.libelleNature = libelleNature;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_NATURE", unique = true, nullable = false)
	public Integer getIdNature() {
		return this.idNature;
	}

	public void setIdNature(Integer idNature) {
		this.idNature = idNature;
	}

	@Column(name = "CODE_NATURE", length = 10)
	public String getCodeNature() {
		return this.codeNature;
	}

	public void setCodeNature(String codeNature) {
		this.codeNature = codeNature;
	}

	@Column(name = "LIBELLE_NATURE", length = 30)
	public String getLibelleNature() {
		return this.libelleNature;
	}

	public void setLibelleNature(String libelleNature) {
		this.libelleNature = libelleNature;
	}

}
