package com.daaje.model;
// Generated 19 sept. 2023, 10:50:45 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NatureProjet generated by hbm2java
 */
@Entity
@Table(name = "nature_projet", catalog = "sygca_bd")
public class NatureProjet implements java.io.Serializable {

	private Integer idNatureProjet;
	private String codeNatureProjet;
	private String libelleNatureProjet;
	private Set<Centre> centres = new HashSet<Centre>(0);

	public NatureProjet() {
	}

	public NatureProjet(String codeNatureProjet, String libelleNatureProjet, Set<Centre> centres) {
		this.codeNatureProjet = codeNatureProjet;
		this.libelleNatureProjet = libelleNatureProjet;
		this.centres = centres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_NATURE_PROJET", unique = true, nullable = false)
	public Integer getIdNatureProjet() {
		return this.idNatureProjet;
	}

	public void setIdNatureProjet(Integer idNatureProjet) {
		this.idNatureProjet = idNatureProjet;
	}

	@Column(name = "CODE_NATURE_PROJET", length = 10)
	public String getCodeNatureProjet() {
		return this.codeNatureProjet;
	}

	public void setCodeNatureProjet(String codeNatureProjet) {
		this.codeNatureProjet = codeNatureProjet;
	}

	@Column(name = "LIBELLE_NATURE_PROJET", length = 30)
	public String getLibelleNatureProjet() {
		return this.libelleNatureProjet;
	}

	public void setLibelleNatureProjet(String libelleNatureProjet) {
		this.libelleNatureProjet = libelleNatureProjet;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "natureProjet")
	public Set<Centre> getCentres() {
		return this.centres;
	}

	public void setCentres(Set<Centre> centres) {
		this.centres = centres;
	}

}
