package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NatureProjet generated by hbm2java
 */
@Entity
@Table(name = "nature_projet", catalog = "sygca_bd")
public class NatureProjet implements java.io.Serializable {

	private Integer idNatureProjet;
	private String codeNatureProjet;
	private String libelleNatureProjet;

	public NatureProjet() {
	}

	public NatureProjet(String codeNatureProjet, String libelleNatureProjet) {
		this.codeNatureProjet = codeNatureProjet;
		this.libelleNatureProjet = libelleNatureProjet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_NATURE_PROJET", unique = true, nullable = false)
	public Integer getIdNatureProjet() {
		return this.idNatureProjet;
	}

	public void setIdNatureProjet(Integer idNatureProjet) {
		this.idNatureProjet = idNatureProjet;
	}

	@Column(name = "CODE_NATURE_PROJET", length = 10)
	public String getCodeNatureProjet() {
		return this.codeNatureProjet;
	}

	public void setCodeNatureProjet(String codeNatureProjet) {
		this.codeNatureProjet = codeNatureProjet;
	}

	@Column(name = "LIBELLE_NATURE_PROJET", length = 30)
	public String getLibelleNatureProjet() {
		return this.libelleNatureProjet;
	}

	public void setLibelleNatureProjet(String libelleNatureProjet) {
		this.libelleNatureProjet = libelleNatureProjet;
	}

}
