package com.daaje.model;
// Generated 19 sept. 2023, 10:50:45 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NiveauFormation generated by hbm2java
 */
@Entity
@Table(name = "niveau_formation", catalog = "sygca_bd")
public class NiveauFormation implements java.io.Serializable {

	private Integer idNiveauFormation;
	private String codeNiveauFormation;
	private String libelleNiveauFormation;
	private String trimestre;
	private Set<Inscription> inscriptions = new HashSet<Inscription>(0);
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);

	public NiveauFormation() {
	}

	public NiveauFormation(String codeNiveauFormation, String libelleNiveauFormation, String trimestre,
			Set<Inscription> inscriptions, Set<Enseigner> enseigners) {
		this.codeNiveauFormation = codeNiveauFormation;
		this.libelleNiveauFormation = libelleNiveauFormation;
		this.trimestre = trimestre;
		this.inscriptions = inscriptions;
		this.enseigners = enseigners;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_NIVEAU_FORMATION", unique = true, nullable = false)
	public Integer getIdNiveauFormation() {
		return this.idNiveauFormation;
	}

	public void setIdNiveauFormation(Integer idNiveauFormation) {
		this.idNiveauFormation = idNiveauFormation;
	}

	@Column(name = "CODE_NIVEAU_FORMATION", length = 10)
	public String getCodeNiveauFormation() {
		return this.codeNiveauFormation;
	}

	public void setCodeNiveauFormation(String codeNiveauFormation) {
		this.codeNiveauFormation = codeNiveauFormation;
	}

	@Column(name = "LIBELLE_NIVEAU_FORMATION", length = 30)
	public String getLibelleNiveauFormation() {
		return this.libelleNiveauFormation;
	}

	public void setLibelleNiveauFormation(String libelleNiveauFormation) {
		this.libelleNiveauFormation = libelleNiveauFormation;
	}

	@Column(name = "TRIMESTRE", length = 15)
	public String getTrimestre() {
		return this.trimestre;
	}

	public void setTrimestre(String trimestre) {
		this.trimestre = trimestre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "niveauFormation")
	public Set<Inscription> getInscriptions() {
		return this.inscriptions;
	}

	public void setInscriptions(Set<Inscription> inscriptions) {
		this.inscriptions = inscriptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "niveauFormation")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

}
