package com.daaje.model;
// Generated 6 sept. 2023, 13:51:33 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profession generated by hbm2java
 */
@Entity
@Table(name = "profession", catalog = "sigca_bd")
public class Profession implements java.io.Serializable {

	private Integer idProfession;
	private int idTypeactivite;
	private int idAnimateur;
	private int idActivite;

	public Profession() {
	}

	public Profession(int idTypeactivite, int idAnimateur, int idActivite) {
		this.idTypeactivite = idTypeactivite;
		this.idAnimateur = idAnimateur;
		this.idActivite = idActivite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PROFESSION", unique = true, nullable = false)
	public Integer getIdProfession() {
		return this.idProfession;
	}

	public void setIdProfession(Integer idProfession) {
		this.idProfession = idProfession;
	}

	@Column(name = "ID_TYPEACTIVITE", nullable = false)
	public int getIdTypeactivite() {
		return this.idTypeactivite;
	}

	public void setIdTypeactivite(int idTypeactivite) {
		this.idTypeactivite = idTypeactivite;
	}

	@Column(name = "ID_ANIMATEUR", nullable = false)
	public int getIdAnimateur() {
		return this.idAnimateur;
	}

	public void setIdAnimateur(int idAnimateur) {
		this.idAnimateur = idAnimateur;
	}

	@Column(name = "ID_ACTIVITE", nullable = false)
	public int getIdActivite() {
		return this.idActivite;
	}

	public void setIdActivite(int idActivite) {
		this.idActivite = idActivite;
	}

}
