package com.daaje.model;
// Generated 10 janv. 2024, 16:03:56 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Profession generated by hbm2java
 */
@Entity
@Table(name = "profession", catalog = "sygca_bd")
public class Profession implements java.io.Serializable {

	private Integer idProfession;
	private Activite activite;
	private Animateur animateur;
	private TypeActivite typeActivite;

	public Profession() {
	}

	public Profession(Activite activite, Animateur animateur, TypeActivite typeActivite) {
		this.activite = activite;
		this.animateur = animateur;
		this.typeActivite = typeActivite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PROFESSION", unique = true, nullable = false)
	public Integer getIdProfession() {
		return this.idProfession;
	}

	public void setIdProfession(Integer idProfession) {
		this.idProfession = idProfession;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTIVITE", nullable = false)
	public Activite getActivite() {
		return this.activite;
	}

	public void setActivite(Activite activite) {
		this.activite = activite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ANIMATEUR", nullable = false)
	public Animateur getAnimateur() {
		return this.animateur;
	}

	public void setAnimateur(Animateur animateur) {
		this.animateur = animateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TYPEACTIVITE", nullable = false)
	public TypeActivite getTypeActivite() {
		return this.typeActivite;
	}

	public void setTypeActivite(TypeActivite typeActivite) {
		this.typeActivite = typeActivite;
	}

}
