package com.daaje.model;
// Generated 25 sept. 2023, 12:18:35 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Progamme generated by hbm2java
 */
@Entity
@Table(name = "progamme", catalog = "sygca_bd")
public class Progamme implements java.io.Serializable {

	private int idPromoteur;
	private Promoteur promoteur;
	private String codePromoteur;
	private String libelleProgramme;

	public Progamme() {
	}

	public Progamme(Promoteur promoteur) {
		this.promoteur = promoteur;
	}

	public Progamme(Promoteur promoteur, String codePromoteur, String libelleProgramme) {
		this.promoteur = promoteur;
		this.codePromoteur = codePromoteur;
		this.libelleProgramme = libelleProgramme;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "promoteur"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "ID_PROMOTEUR", unique = true, nullable = false)
	public int getIdPromoteur() {
		return this.idPromoteur;
	}

	public void setIdPromoteur(int idPromoteur) {
		this.idPromoteur = idPromoteur;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Promoteur getPromoteur() {
		return this.promoteur;
	}

	public void setPromoteur(Promoteur promoteur) {
		this.promoteur = promoteur;
	}

	@Column(name = "CODE_PROMOTEUR", length = 10)
	public String getCodePromoteur() {
		return this.codePromoteur;
	}

	public void setCodePromoteur(String codePromoteur) {
		this.codePromoteur = codePromoteur;
	}

	@Column(name = "LIBELLE_PROGRAMME", length = 30)
	public String getLibelleProgramme() {
		return this.libelleProgramme;
	}

	public void setLibelleProgramme(String libelleProgramme) {
		this.libelleProgramme = libelleProgramme;
	}

}
