package com.daaje.model;
// Generated 2 nov. 2023, 15:04:15 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Responsable generated by hbm2java
 */
@Entity
@Table(name = "responsable", catalog = "sygca_bd")
public class Responsable implements java.io.Serializable {

	private Integer idResponsable;
	private Fonction fonction;
	private String matriculeResponsable;
	private String nomResponsable;
	private String prenomResponsable;
	private String telephoneResponsable;
	private String adresseResponsable;
	private Date datePriseService;
	private Date dateRetraite;
	private Date dateNaissance;
	private String mailResponsable;
	private Set<ServiceResponsable> serviceResponsables = new HashSet<ServiceResponsable>(0);

	public Responsable() {
	}

	public Responsable(Fonction fonction) {
		this.fonction = fonction;
	}

	public Responsable(Fonction fonction, String matriculeResponsable, String nomResponsable, String prenomResponsable,
			String telephoneResponsable, String adresseResponsable, Date datePriseService, Date dateRetraite,
			Date dateNaissance, String mailResponsable, Set<ServiceResponsable> serviceResponsables) {
		this.fonction = fonction;
		this.matriculeResponsable = matriculeResponsable;
		this.nomResponsable = nomResponsable;
		this.prenomResponsable = prenomResponsable;
		this.telephoneResponsable = telephoneResponsable;
		this.adresseResponsable = adresseResponsable;
		this.datePriseService = datePriseService;
		this.dateRetraite = dateRetraite;
		this.dateNaissance = dateNaissance;
		this.mailResponsable = mailResponsable;
		this.serviceResponsables = serviceResponsables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_RESPONSABLE", unique = true, nullable = false)
	public Integer getIdResponsable() {
		return this.idResponsable;
	}

	public void setIdResponsable(Integer idResponsable) {
		this.idResponsable = idResponsable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FONCTION", nullable = false)
	public Fonction getFonction() {
		return this.fonction;
	}

	public void setFonction(Fonction fonction) {
		this.fonction = fonction;
	}

	@Column(name = "MATRICULE_RESPONSABLE", length = 10)
	public String getMatriculeResponsable() {
		return this.matriculeResponsable;
	}

	public void setMatriculeResponsable(String matriculeResponsable) {
		this.matriculeResponsable = matriculeResponsable;
	}

	@Column(name = "NOM_RESPONSABLE", length = 30)
	public String getNomResponsable() {
		return this.nomResponsable;
	}

	public void setNomResponsable(String nomResponsable) {
		this.nomResponsable = nomResponsable;
	}

	@Column(name = "PRENOM_RESPONSABLE", length = 30)
	public String getPrenomResponsable() {
		return this.prenomResponsable;
	}

	public void setPrenomResponsable(String prenomResponsable) {
		this.prenomResponsable = prenomResponsable;
	}

	@Column(name = "TELEPHONE_RESPONSABLE", length = 10)
	public String getTelephoneResponsable() {
		return this.telephoneResponsable;
	}

	public void setTelephoneResponsable(String telephoneResponsable) {
		this.telephoneResponsable = telephoneResponsable;
	}

	@Column(name = "ADRESSE_RESPONSABLE", length = 20)
	public String getAdresseResponsable() {
		return this.adresseResponsable;
	}

	public void setAdresseResponsable(String adresseResponsable) {
		this.adresseResponsable = adresseResponsable;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_PRISE_SERVICE", length = 10)
	public Date getDatePriseService() {
		return this.datePriseService;
	}

	public void setDatePriseService(Date datePriseService) {
		this.datePriseService = datePriseService;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_RETRAITE", length = 10)
	public Date getDateRetraite() {
		return this.dateRetraite;
	}

	public void setDateRetraite(Date dateRetraite) {
		this.dateRetraite = dateRetraite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISSANCE", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "MAIL_RESPONSABLE", length = 30)
	public String getMailResponsable() {
		return this.mailResponsable;
	}

	public void setMailResponsable(String mailResponsable) {
		this.mailResponsable = mailResponsable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsable")
	public Set<ServiceResponsable> getServiceResponsables() {
		return this.serviceResponsables;
	}

	public void setServiceResponsables(Set<ServiceResponsable> serviceResponsables) {
		this.serviceResponsables = serviceResponsables;
	}

}
