package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceResponsable generated by hbm2java
 */
@Entity
@Table(name = "service_responsable", catalog = "sygca_bd")
public class ServiceResponsable implements java.io.Serializable {

	private Integer idServiceDrena;
	private Integer attributIdIepp16;
	private Integer idResponsable;
	private Integer idDrena;
	private String codeService;
	private Date dateArrivee;
	private Date dateDepart;

	public ServiceResponsable() {
	}

	public ServiceResponsable(Integer attributIdIepp16, Integer idResponsable, Integer idDrena, String codeService,
			Date dateArrivee, Date dateDepart) {
		this.attributIdIepp16 = attributIdIepp16;
		this.idResponsable = idResponsable;
		this.idDrena = idDrena;
		this.codeService = codeService;
		this.dateArrivee = dateArrivee;
		this.dateDepart = dateDepart;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_SERVICE_DRENA", unique = true, nullable = false)
	public Integer getIdServiceDrena() {
		return this.idServiceDrena;
	}

	public void setIdServiceDrena(Integer idServiceDrena) {
		this.idServiceDrena = idServiceDrena;
	}

	@Column(name = "ATTRIBUT_ID_IEPP16")
	public Integer getAttributIdIepp16() {
		return this.attributIdIepp16;
	}

	public void setAttributIdIepp16(Integer attributIdIepp16) {
		this.attributIdIepp16 = attributIdIepp16;
	}

	@Column(name = "ID_RESPONSABLE")
	public Integer getIdResponsable() {
		return this.idResponsable;
	}

	public void setIdResponsable(Integer idResponsable) {
		this.idResponsable = idResponsable;
	}

	@Column(name = "ID_DRENA")
	public Integer getIdDrena() {
		return this.idDrena;
	}

	public void setIdDrena(Integer idDrena) {
		this.idDrena = idDrena;
	}

	@Column(name = "CODE_SERVICE", length = 10)
	public String getCodeService() {
		return this.codeService;
	}

	public void setCodeService(String codeService) {
		this.codeService = codeService;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ARRIVEE", length = 10)
	public Date getDateArrivee() {
		return this.dateArrivee;
	}

	public void setDateArrivee(Date dateArrivee) {
		this.dateArrivee = dateArrivee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEPART", length = 10)
	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

}
