package com.daaje.model;
// Generated 15 sept. 2023, 12:30:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SousPrefecture generated by hbm2java
 */
@Entity
@Table(name = "sous_prefecture", catalog = "sygca_bd")
public class SousPrefecture implements java.io.Serializable {

	private Integer idPrefecture;
	private String codePrefecture;
	private String nomPrefecture;

	public SousPrefecture() {
	}

	public SousPrefecture(String codePrefecture, String nomPrefecture) {
		this.codePrefecture = codePrefecture;
		this.nomPrefecture = nomPrefecture;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PREFECTURE", unique = true, nullable = false)
	public Integer getIdPrefecture() {
		return this.idPrefecture;
	}

	public void setIdPrefecture(Integer idPrefecture) {
		this.idPrefecture = idPrefecture;
	}

	@Column(name = "CODE_PREFECTURE", length = 10)
	public String getCodePrefecture() {
		return this.codePrefecture;
	}

	public void setCodePrefecture(String codePrefecture) {
		this.codePrefecture = codePrefecture;
	}

	@Column(name = "NOM_PREFECTURE", length = 30)
	public String getNomPrefecture() {
		return this.nomPrefecture;
	}

	public void setNomPrefecture(String nomPrefecture) {
		this.nomPrefecture = nomPrefecture;
	}

}
