package com.daaje.model;
// Generated 6 sept. 2023, 13:51:33 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SousPrefecture generated by hbm2java
 */
@Entity
@Table(name = "sous_prefecture", catalog = "sigca_bd")
public class SousPrefecture implements java.io.Serializable {

	private Integer idPrefecture;
	private String codePrefecture;
	private String nomPrefecture;
	private Set<Centre> centres = new HashSet<Centre>(0);

	public SousPrefecture() {
	}

	public SousPrefecture(String codePrefecture, String nomPrefecture, Set<Centre> centres) {
		this.codePrefecture = codePrefecture;
		this.nomPrefecture = nomPrefecture;
		this.centres = centres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PREFECTURE", unique = true, nullable = false)
	public Integer getIdPrefecture() {
		return this.idPrefecture;
	}

	public void setIdPrefecture(Integer idPrefecture) {
		this.idPrefecture = idPrefecture;
	}

	@Column(name = "CODE_PREFECTURE", length = 10)
	public String getCodePrefecture() {
		return this.codePrefecture;
	}

	public void setCodePrefecture(String codePrefecture) {
		this.codePrefecture = codePrefecture;
	}

	@Column(name = "NOM_PREFECTURE", length = 30)
	public String getNomPrefecture() {
		return this.nomPrefecture;
	}

	public void setNomPrefecture(String nomPrefecture) {
		this.nomPrefecture = nomPrefecture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sousPrefecture")
	public Set<Centre> getCentres() {
		return this.centres;
	}

	public void setCentres(Set<Centre> centres) {
		this.centres = centres;
	}

}
