package com.daaje.model;
// Generated 8 avr. 2024, 14:52:14 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeActivite generated by hbm2java
 */
@Entity
@Table(name = "type_activite", catalog = "sygca_bd")
public class TypeActivite implements java.io.Serializable {

	private Integer idTypeactivite;
	private String codeTypeactivite;
	private String libelleTypeactivite;
	private Set<Profession> professions = new HashSet<Profession>(0);

	public TypeActivite() {
	}

	public TypeActivite(String codeTypeactivite, String libelleTypeactivite, Set<Profession> professions) {
		this.codeTypeactivite = codeTypeactivite;
		this.libelleTypeactivite = libelleTypeactivite;
		this.professions = professions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TYPEACTIVITE", unique = true, nullable = false)
	public Integer getIdTypeactivite() {
		return this.idTypeactivite;
	}

	public void setIdTypeactivite(Integer idTypeactivite) {
		this.idTypeactivite = idTypeactivite;
	}

	@Column(name = "CODE_TYPEACTIVITE", length = 10)
	public String getCodeTypeactivite() {
		return this.codeTypeactivite;
	}

	public void setCodeTypeactivite(String codeTypeactivite) {
		this.codeTypeactivite = codeTypeactivite;
	}

	@Column(name = "LIBELLE_TYPEACTIVITE", length = 30)
	public String getLibelleTypeactivite() {
		return this.libelleTypeactivite;
	}

	public void setLibelleTypeactivite(String libelleTypeactivite) {
		this.libelleTypeactivite = libelleTypeactivite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeActivite")
	public Set<Profession> getProfessions() {
		return this.professions;
	}

	public void setProfessions(Set<Profession> professions) {
		this.professions = professions;
	}

}
