package com.daaje.model;
// Generated 13 f�vr. 2024, 11:13:45 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeAlphabetisation generated by hbm2java
 */
@Entity
@Table(name = "type_alphabetisation", catalog = "sygca_bd")
public class TypeAlphabetisation implements java.io.Serializable {

	private Integer idTypeAlpha;
	private String codeTypeAlpha;
	private String libTypeAlpha;
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);

	public TypeAlphabetisation() {
	}

	public TypeAlphabetisation(String codeTypeAlpha, String libTypeAlpha, Set<Enseigner> enseigners) {
		this.codeTypeAlpha = codeTypeAlpha;
		this.libTypeAlpha = libTypeAlpha;
		this.enseigners = enseigners;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TYPE_ALPHA", unique = true, nullable = false)
	public Integer getIdTypeAlpha() {
		return this.idTypeAlpha;
	}

	public void setIdTypeAlpha(Integer idTypeAlpha) {
		this.idTypeAlpha = idTypeAlpha;
	}

	@Column(name = "CODE_TYPE_ALPHA", length = 10)
	public String getCodeTypeAlpha() {
		return this.codeTypeAlpha;
	}

	public void setCodeTypeAlpha(String codeTypeAlpha) {
		this.codeTypeAlpha = codeTypeAlpha;
	}

	@Column(name = "LIB_TYPE_ALPHA", length = 25)
	public String getLibTypeAlpha() {
		return this.libTypeAlpha;
	}

	public void setLibTypeAlpha(String libTypeAlpha) {
		this.libTypeAlpha = libTypeAlpha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeAlphabetisation")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

}
