package com.daaje.model;
// Generated 20 sept. 2023, 12:20:34 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Commune generated by hbm2java
 */
@Entity
@Table(name = "commune", catalog = "sygca_bd")
public class Commune implements java.io.Serializable {

	private Integer idCommune;
	private SousPrefecture sousPrefecture;
	private String codeCommune;
	private String nomCommune;
	private Set<LocaliteDImplantation> localiteDImplantations = new HashSet<LocaliteDImplantation>(0);

	public Commune() {
	}

	public Commune(SousPrefecture sousPrefecture) {
		this.sousPrefecture = sousPrefecture;
	}

	public Commune(SousPrefecture sousPrefecture, String codeCommune, String nomCommune,
			Set<LocaliteDImplantation> localiteDImplantations) {
		this.sousPrefecture = sousPrefecture;
		this.codeCommune = codeCommune;
		this.nomCommune = nomCommune;
		this.localiteDImplantations = localiteDImplantations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_COMMUNE", unique = true, nullable = false)
	public Integer getIdCommune() {
		return this.idCommune;
	}

	public void setIdCommune(Integer idCommune) {
		this.idCommune = idCommune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PREFECTURE", nullable = false)
	public SousPrefecture getSousPrefecture() {
		return this.sousPrefecture;
	}

	public void setSousPrefecture(SousPrefecture sousPrefecture) {
		this.sousPrefecture = sousPrefecture;
	}

	@Column(name = "CODE_COMMUNE", length = 10)
	public String getCodeCommune() {
		return this.codeCommune;
	}

	public void setCodeCommune(String codeCommune) {
		this.codeCommune = codeCommune;
	}

	@Column(name = "NOM_COMMUNE", length = 30)
	public String getNomCommune() {
		return this.nomCommune;
	}

	public void setNomCommune(String nomCommune) {
		this.nomCommune = nomCommune;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commune")
	public Set<LocaliteDImplantation> getLocaliteDImplantations() {
		return this.localiteDImplantations;
	}

	public void setLocaliteDImplantations(Set<LocaliteDImplantation> localiteDImplantations) {
		this.localiteDImplantations = localiteDImplantations;
	}

}
