package com.daaje.model;
// Generated 20 sept. 2023, 12:20:34 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Iep generated by hbm2java
 */
@Entity
@Table(name = "iep", catalog = "sygca_bd")
public class Iep implements java.io.Serializable {

	private Integer aidIep;
	private Drena drena;
	private String codeIep;
	private String nomIep;
	private String mailIep;
	private Set<ServiceResponsable> serviceResponsables = new HashSet<ServiceResponsable>(0);
	private Set<Centre> centres = new HashSet<Centre>(0);

	public Iep() {
	}

	public Iep(Drena drena) {
		this.drena = drena;
	}

	public Iep(Drena drena, String codeIep, String nomIep, String mailIep, Set<ServiceResponsable> serviceResponsables,
			Set<Centre> centres) {
		this.drena = drena;
		this.codeIep = codeIep;
		this.nomIep = nomIep;
		this.mailIep = mailIep;
		this.serviceResponsables = serviceResponsables;
		this.centres = centres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AID_IEP", unique = true, nullable = false)
	public Integer getAidIep() {
		return this.aidIep;
	}

	public void setAidIep(Integer aidIep) {
		this.aidIep = aidIep;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DRENA", nullable = false)
	public Drena getDrena() {
		return this.drena;
	}

	public void setDrena(Drena drena) {
		this.drena = drena;
	}

	@Column(name = "CODE_IEP", length = 10)
	public String getCodeIep() {
		return this.codeIep;
	}

	public void setCodeIep(String codeIep) {
		this.codeIep = codeIep;
	}

	@Column(name = "NOM_IEP", length = 30)
	public String getNomIep() {
		return this.nomIep;
	}

	public void setNomIep(String nomIep) {
		this.nomIep = nomIep;
	}

	@Column(name = "MAIL_IEP", length = 30)
	public String getMailIep() {
		return this.mailIep;
	}

	public void setMailIep(String mailIep) {
		this.mailIep = mailIep;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iep")
	public Set<ServiceResponsable> getServiceResponsables() {
		return this.serviceResponsables;
	}

	public void setServiceResponsables(Set<ServiceResponsable> serviceResponsables) {
		this.serviceResponsables = serviceResponsables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iep")
	public Set<Centre> getCentres() {
		return this.centres;
	}

	public void setCentres(Set<Centre> centres) {
		this.centres = centres;
	}

}
