package com.daaje.model;
// Generated 20 sept. 2023, 12:20:34 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SousPrefecture generated by hbm2java
 */
@Entity
@Table(name = "sous_prefecture", catalog = "sygca_bd")
public class SousPrefecture implements java.io.Serializable {

	private Integer idPrefecture;
	private Departement departement;
	private String codePrefecture;
	private String nomPrefecture;
	private Set<Commune> communes = new HashSet<Commune>(0);

	public SousPrefecture() {
	}

	public SousPrefecture(Departement departement) {
		this.departement = departement;
	}

	public SousPrefecture(Departement departement, String codePrefecture, String nomPrefecture, Set<Commune> communes) {
		this.departement = departement;
		this.codePrefecture = codePrefecture;
		this.nomPrefecture = nomPrefecture;
		this.communes = communes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PREFECTURE", unique = true, nullable = false)
	public Integer getIdPrefecture() {
		return this.idPrefecture;
	}

	public void setIdPrefecture(Integer idPrefecture) {
		this.idPrefecture = idPrefecture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_DEPARTEMENT", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "CODE_PREFECTURE", length = 10)
	public String getCodePrefecture() {
		return this.codePrefecture;
	}

	public void setCodePrefecture(String codePrefecture) {
		this.codePrefecture = codePrefecture;
	}

	@Column(name = "NOM_PREFECTURE", length = 30)
	public String getNomPrefecture() {
		return this.nomPrefecture;
	}

	public void setNomPrefecture(String nomPrefecture) {
		this.nomPrefecture = nomPrefecture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sousPrefecture")
	public Set<Commune> getCommunes() {
		return this.communes;
	}

	public void setCommunes(Set<Commune> communes) {
		this.communes = communes;
	}

}
